namespace Core
{
    public enum ItemType
    {
        Invalid,
        Limestone,
        LimestoneBrick,
        LimestoneDoubleBrick,
        Dirt,
        Wood,
        Stick,
        Leaves,
        Arrowhead,
        ToolShaft,
        Log,
        IronBar,
        IronSiliconSlag,
        CopperBar,
        IronPickaxe,
        Conveyor,
        AnthraciteCoal,
        BituminousCoal,
        LigniteCoal,
        Mineshaft,
        ClayFurnace,
        Sorter,
        Depot,
        Chalcopyrite,
        Magnetite
    }
}